//returns a surveyjs page component which contains a bootstrap themed card
    var WelcomePage = (surveyName) =>{
        return( 
      {
        "name": "page1",
        "title": {surveyName},
        "elements": [
            {
                "type": "panel",
                "title": "",
                "elements": [
                    {
                        "type": "html",
                        "name": "testHtml",
                        "html": `
                        <div class="px-4 py-5 my-5 text-center">
                        <!--<img class="d-block mx-auto mb-4" src="/survey/public/logo_snet_long.png" alt="snet logo large" width="72" height="57"-->
                        <h1 class="display-5 fw-bold">${surveyName}</h1>
                        <div class="col-lg-6 mx-auto">
                          <p class="lead mb-4">Welcome to ${surveyName}. Please click Start to begin the survey.</p>
                         
                          <div class=instructions>
                            <h4>Purpose of the survey</h4>
                            <p>The purpose of the survey is to collect preferences of the user regarding the shown items (movies) </p>
                            <h4>Instructions</h4>
                            <ul>
                              <li>Observe the movies shown on each page and rate them from 0 to 5 if you've seen it.</li>
                              <li>If you've not already seen it, click on don't know and then next</li>
                              <li>You'll be shown two lists of movies generated by two algorithms that we are testing </li>
                              <li>Observe these lists and answer the questions shown at the end of the lists by scroling right until the end of the list. </li>
                            </ul>
                          <h4>Contact</h4>
                          <a href="mailto:ananta.lamichhane@tu-berlin.de">ananta.lamichhane@tu-berlin.de</a>
                          <h4>About</h4>
                          <p>This project is a part of masters thesis at chair <a href="https://snet.tu-berlin.de" class="link-primary">SNET TU Berlin</a>.
                          It aims to provide a platform for recommender systems researchers to conduct user
                          studies by filling up a survey.</p>
                          </div>
                        </div>
                      </div>
                      `
                    }
                ]
            }
        ]

    })
}

export default  WelcomePage